language: swift
osx_image: xcode10.2

env:
  global:
  - LANG=en_US.UTF-8
  - PROJECT="SwiftyFlow/SwiftyFlow.xcodeproj"
  - SCHEME="SwiftyFlow"
  - APP_NAME="SwiftyFlow"
  - EMAILS="felipeflorencio@me.com"
  matrix:
  - DESTINATION="platform=iOS Simulator,OS=12.2,name=iPhone X" SDK="iphoneos12.2"
  
script:
  - xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  - xcodebuild clean build test -enableCodeCoverage YES -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO